In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

In [6]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
y = tf.zeros((3,3))
print(y)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [13]:
z = tf.ones((3,3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [14]:
i = tf.eye(3)  #identity matrix
print(i)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
z = tf.range(start=0, limit=10, delta=2)
print(z)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [16]:
# convert to different dtypes
z = tf.cast(z, dtype=tf.float32)
print(z)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float32)


In [5]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])
z = tf.add(x, y)
print(z)

tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)


In [6]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [8]:
x = tf.constant([43,7,8,2,3,1,2])
print(x[::2])
print(x[::-1])

tf.Tensor([43  8  3  2], shape=(4,), dtype=int32)
tf.Tensor([ 2  1  3  2  8  7 43], shape=(7,), dtype=int32)


In [11]:
x = tf.range(9)
print(x)
x_reshape = tf.reshape(x, (3,3))
print(x_reshape)
x_transpose = tf.transpose(x_reshape)
print(x_transpose)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
